---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  refreshInterval: 5m
  target:
    name: searxng-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SEARXNG_SECRET: "bff92a9c8f84d3157c22df3f0b0a4a3d"
  dataFrom:
    - extract:
        key: searxng
      rewrite:
        - regexp:
            source: "(.*)"
            target: "searxng_$1"
