---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      searxng:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: 2025.1.10-94a0b415e
            env:
              HTTP_PORT: &port 8080
              LOG_WITHOUT_NEWLINE: true
              LOG_IGNORE_PATH: /
              PROMETHEUS_ENABLED: true
              SEARXNG_REDIS_URL: redis://searxng-redis.utilities.svc.cluster.local:6379/0
              SEARXNG_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: searxng-secret-key
                    key: SEARXNG_SECRET_KEY
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
      redis:
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
        strategy: RollingUpdate
        containers:
          redis:
            image:
              repository: docker.io/valkey/valkey
              tag: 8.0.2
            args:
              - --save
              - ""
              - --appendonly
              - "no"
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    # defaultPodOptions:
      # securityContext:
        # runAsNonRoot: true
        # runAsUser: 65534
        # runAsGroup: 65534
        # seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: searxng
        ports:
          http:
            port: *port
      redis:
        controller: redis
        ports:
          http:
            port: 6379
    serviceMonitor:
      app:
        serviceName: searxng
        endpoints:
          - port: http
            scheme: http
            path: /
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "SearXNG"
          gethomepage.dev/description: "An Internet metasearch engine"
          gethomepage.dev/group: "Utilities"
          gethomepage.dev/icon: "searxng.png"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: configMap
        name: searxng-configmap
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmpfs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /etc/searxng
          - path: /tmp
