---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - ./resources/limiter.toml
      - ./resources/settings.yml
generatorOptions:
  disableNameSuffixHash: true
