---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: v1.8.1
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultClassReplicaCount: 3
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Longhorn"
        gethomepage.dev/description: "Longhorn cluster storage"
        gethomepage.dev/group: "Cluster Management"
        gethomepage.dev/icon: "longhorn.png"
        nginx.ingress.kubernetes.io/rewrite-target: /
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "${SECRET_DOMAIN/./-}-production-tls"
