apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:N1T02/8QTBVvauVjdbEdrgJwEpn832dFYoPoXmITM0tcaO8hbAsQVA==,iv:9GPpNInFJ2hZnof8gplTZEBBWMnF3UnAsUyyHErdCHQ=,tag:t5hWT5Sp+MU6TSI1kQiWwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u92vmxr2k60y7mzumzdcmha780meu9smt0dewvj6ch38f2fcxe6s6txz88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOWFqM0tZVlgrSHArNnI1
            ekYxc1dmcU9WdnJwczRaWklzdGJyb2s3MFNBCkFLdjdtYTFIYlFtVkptWmFHWVF2
            OFJsNjZYY3pheFU0Z0Q1WGpDbTBKaGsKLS0tIC8xZlAyN2RSYnRvenl3ZUlEUEww
            R2djSXkvR09BaFdJR2IvbDl5bDhyYVEKDYTs+vzsXGmy6y9BRY5ZwJWWdORarJEY
            w4l1AZjTrEVD6EX9xv/p2L5u2FcnQRNSyAIiUJ/exsdYaz+789kb+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T13:58:47Z"
    mac: ENC[AES256_GCM,data:idX4GIF2LfYzMSblnG/XUPdmJfw+Ykw1u1fjjE0vaW8cniWuIgnhzxeYIR71LWDUN8UvzI6i4vp82lOn9tL7x0skpq6qWhJSDqWjfwzTypHrhRXR0UzwWLIXih1D5oDwJAozHexr/xV30SMhD2SLjIt3cqyLVhz9137cBeneZRQ=,iv:qMS7zrJTnk+nKuftpVlulTuLcyxCEzKCgW1TQgu3wzw=,tag:IvqecnZ2FsrmF/H7mYZcWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
