apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DEsxWgaAUyixfd865WrPlePyowghv5DrIdDSER1xqvxPhGGZhW/GZg==,iv:rKXgMZa6+21Sm6wzLL30r1THieTvIcydnskLOiF9i9Y=,tag:7WUqfIeWUi2a4sgqB0tsSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u92vmxr2k60y7mzumzdcmha780meu9smt0dewvj6ch38f2fcxe6s6txz88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeFJ2dnRNekxxL1B4TGxw
            Nlo3OWpoZFAxSWlvUGlLNFpqWWJmSDBOMHlJCk9vSHJ6YkZhQm5YL25VL01tRGVT
            T1ZxT0NyTkhjNVQrWnJSWkNhWHdNSXMKLS0tIGhIUnJBOWdGSHFRb2h3b2RGSThk
            dHFqSXNqSDhtUzRQWGo3U3lqTjA0WWcKWnpkFCx7oVRkUKNqFbUO9/Ff3Q8ANunt
            Nkfa4EM+EhNbLVAE+56nh6TwAJT8pi4yc8rAQIiOWBjeIUjXT/2pQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T12:34:11Z"
    mac: ENC[AES256_GCM,data:FAKlcY5Z5xVxP6Ll3OssHhqDtEOgIMqGrSZ4Aqx4+15vbpirM0mMwS3UPmcltdba67T/RHWfE0Lgk98r/RRcvdDjgRzDkFYsGVICMG3S09+P9bL8dwcErGmbIF8k+AJXeeywNcmOyuE01H2HQz29acrkTzf2iQ/zYXqCrKnX+6o=,iv:/uXa/gxnLtyoMQOb4+HZksyMx0OY0MneNf4ERFJsyXo=,tag:FfLd3Ezv4LvLg5RUCkWX5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
