---
- datetime:
  text_size: xl
  format:
    dateStyle: short
    timeStyle: short
    hour12: true

- greeting:
    text_size: xl
    text: Homepage

- openweathermap:
    label: Phoenix
    latitude: ${HOMEPAGE_VAR_OPENWEATHERMAP_LATITUDE}
    longitude: ${HOMEPAGE_VAR_OPENWEATHERMAP_LONGITUDE}
    units: imperial
    provider: openweathermap
    cache: 5
    format:
      maximumFractionDigits: 1

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- search:
    provider: custom
    url: https://searxng.papagolab.com/search?q=
    target: _blank
