---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      adguard:
        pod:
          dnsConfig:
            options:
              - { name: ndots, value: "1" }
          securityContext:
            runAsNonRoot: false # Adguard doesn't support running as non-root
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        # initContainers:
        #   init-config:
        #     image: &configSyncImage
        #       repository: ghcr.io/kiwigrid/k8s-sidecar
        #       tag: 1.30.1@sha256:439c5ac985827e6a85ad4490a66320b62aefd9e8c6d06fdb1d9c83d582f8a902
        #     env:
        #       FOLDER: /opt/adguardhome/conf
        #       LABEL: app.kubernetes.io/config-owner
        #       LABEL_VALUE: *app
        #       UNIQUE_FILENAMES: false
        #       METHOD: LIST
        #     resources: &configSyncResources
        #       requests:
        #         cpu: 10m
        #         memory: 10Mi
        #       limits:
        #         memory: 128Mi
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.57@sha256:8ed4b2584d04dfb39e6d8fce1fec0304ed19853e4b41f0ea430dbb3fbf3d799b
            securityContext:
              capabilities:
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
            env:
              TZ: ${TIMEZONE}
              TLS_CERTIFICATE_PATH: /opt/adguardhome/certs/tls.crt
              TLS_PRIVATE_KEY_PATH: /opt/adguardhome/certs/tls.key
            envFrom:
              - secretRef:
                  name: adguard-auth
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: false
            #     type: TCP
            #   readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 1G
              limits:
                memory: 3G
          # config-sync:
          #   image: *configSyncImage
          #   env:
          #     FOLDER: /opt/adguardhome/conf
          #     LABEL: app.kubernetes.io/config-owner
          #     LABEL_VALUE: *app
          #     UNIQUE_FILENAMES: false
          #     METHOD: WATCH
          #   resources: *configSyncResources
    # serviceMonitor:
    #   app:
    #     serviceName: adguard
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /
    #         interval: 1m
    #         scrapeTimeout: 10s
    service:
      app:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: "192.168.70.40"
        ports:
          http:
            enabled: true
            port: 80
            protocol: TCP
            targetPort: 80
          # https:
          #   enabled: true
          #   port: &https-port 443
          #   protocol: TCP
          #   targetPort: *https-port
          dns-tcp:
            enabled: true
            port: &dns-port 53
            protocol: TCP
            targetPort: *dns-port
          dns-udp:
            enabled: true
            port: *dns-port
            protocol: UDP
            targetPort: *dns-port
          dot:
            enabled: true
            port: &dot-port 853
            protocol: TCP
            targetPort: *dot-port
          # doh:
          #   enabled: true
          #   port: *https-port
          #   protocol: UDP
          #   targetPort: *https-port
          doq:
            enabled: true
            port: &doq-port 853
            protocol: UDP
            targetPort: *doq-port
          setup:
            enabled: true
            port: &setup-port 3000
            protocol: TCP
            targetPort: *setup-port
    # ingress:
    #   app:
    #     annotations:
    #       gethomepage.dev/enabled: "true"
    #       gethomepage.dev/name: AdGuard
    #       gethomepage.dev/description: "DNS Ad-Blocking"
    #       gethomepage.dev/group: Network
    #       gethomepage.dev/icon: adguard-home.svg
    #     hosts:
    #       - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: app
    #               port: http

    # Required for the config sync init container
    serviceAccount:
      create: true
      name: *app

    persistence:
      config-work:
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /opt/adguardhome/work
      config-conf:
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /opt/adguardhome/conf
      certs:
        enabled: true
        type: secret
        name: adguard-tls-secret
        globalMounts:
          - path: /opt/adguardhome/certs
            readOnly: true
