apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-configmap
  namespace: utilities
  labels:
    app: homepage
data:
  bookmarks.yaml: ""
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: ""
  settings.yaml: |
    title: "${HOMEPAGE_FILE_HOMEPAGE_TITLE}"

    theme: dark
    color: slate

    cardBlur: md

    headerStyle: clean

    providers:
      openweathermap: "${OPENWEATHERMAP_TOKEN}"

    fiveColumns: true
    useEqualHeights: true

    disableTraefik: true

  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: true

    - greeting:
        text_size: xl
        text: Homepage

    - openweathermap:
        label: Phoenix
        latitude: "${OPENWEATHERMAP_LATITUDE}"
        longitude: "${OPENWEATHERMAP_LONGITUDE}"
        units: imperial
        provider: openweathermap
        cache: 5
        format:
          maximumFractionDigits: 1

    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - search:
        provider: custom
        url: "https://searxng.papagolab.com/search?q="
        target: _blank
