---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.10.9
            env:
              PORT: &port 3000
              OPENWEATHERMAP_LATITUDE:
                valueFrom:
                  secretKeyRef:
                    name: homepage-secrets
                    key: OPENWEATHERMAP_LATITUDE
              OPENWEATHERMAP_LONGITUDE:
                valueFrom:
                  secretKeyRef:
                    name: homepage-secrets
                    key: OPENWEATHERMAP_LONGITUDE
            volumeMounts:
              - name: config
                mountPath: /app/config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
    serviceAccount:
      create: true
      name: homepage
      automountServiceAccountToken: true
    # RBAC for service discovery
    additionalControllers:
      rbac:
        type: clusterrole
        clusterrole:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["namespaces", "pods", "nodes"]
              verbs: ["get", "list"]
            - apiGroups: ["extensions", "networking.k8s.io"]
              resources: ["ingresses"]
              verbs: ["get", "list"]
            - apiGroups: ["metrics.k8s.io"]
              resources: ["nodes", "pods"]
              verbs: ["get", "list"]
        clusterrolebinding:
          create: true
          name: homepage
          subjects:
            - kind: ServiceAccount
              name: homepage
              namespace: homepage
    # defaultPodOptions:
    # securityContext:
    # runAsNonRoot: true
    # runAsUser: 65534
    # runAsGroup: 65534
    # seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: homepage
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: homepage
        endpoints:
          - port: http
            scheme: http
            path: /
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
            readOnly: true
          - path: /app/config/docker.yaml
            subPath: docker.yaml
            readOnly: true
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
            readOnly: true
          - path: /app/config/services.yaml
            subPath: services.yaml
            readOnly: true
          - path: /app/config/settings.yaml
            subPath: settings.yaml
            readOnly: true
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
            readOnly: true
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs
