---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: homepage-configmap
    files:
      - ./resources/bookmarks.yaml
      - ./resources/custom.css
      - ./resources/custom.js
      - ./resources/docker.yaml
      - ./resources/kubernetes.yaml
      - ./resources/services.yaml
      - ./resources/settings.yaml
      - ./resources/widgets.yaml
generatorOptions:
  disableNameSuffixHash: true
