---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externaldns.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ./secret.sops.yaml
  - ./resources/adguard-config.sops.yaml
